//! Project generator — produces real, runnable project scaffolds.

use serde::{Deserialize, Serialize};
use smol_str::SmolStr;

/// A project spec — what to generate.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProjectSpec {
    /// Project name.
    pub name: SmolStr,
    /// Project kind: "rust_cli", "rust_lib", "nextjs", "tauri", etc.
    pub kind: SmolStr,
    /// Output directory (absolute or relative to workspace).
    pub output_dir: String,
    /// Optional description.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// A generated file.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GeneratedFile {
    /// Relative path within the project.
    pub path: String,
    /// File content.
    pub content: String,
}

/// Project generator.
pub struct ProjectGenerator;

impl ProjectGenerator {
    /// Generate a project from a spec. Returns the list of files to
    /// write. The caller (an Effect executor) writes them to disk.
    pub fn generate(spec: &ProjectSpec) -> Vec<GeneratedFile> {
        match spec.kind.as_str() {
            "rust_cli" => Self::generate_rust_cli(spec),
            "rust_lib" => Self::generate_rust_lib(spec),
            "nextjs" => Self::generate_nextjs(spec),
            "tauri" => Self::generate_tauri(spec),
            _ => Self::generate_generic(spec),
        }
    }

    fn generate_rust_cli(spec: &ProjectSpec) -> Vec<GeneratedFile> {
        let name = &spec.name;
        vec![
            GeneratedFile {
                path: "Cargo.toml".into(),
                content: format!(
                    "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n",
                    name = name
                ),
            },
            GeneratedFile {
                path: "src/main.rs".into(),
                content: format!(
                    "fn main() {{\n    println!(\"Hello from {}!\");\n}}\n",
                    name
                ),
            },
            GeneratedFile {
                path: "README.md".into(),
                content: format!("# {}\n\nGenerated by SPS Software Factory.\n", name),
            },
        ]
    }

    fn generate_rust_lib(spec: &ProjectSpec) -> Vec<GeneratedFile> {
        let name = &spec.name;
        vec![
            GeneratedFile {
                path: "Cargo.toml".into(),
                content: format!(
                    "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n",
                    name = name
                ),
            },
            GeneratedFile {
                path: "src/lib.rs".into(),
                content: format!(
                    "//! {} library.\n\npub fn version() -> &'static str {{\n    \"0.1.0\"\n}}\n",
                    name
                ),
            },
        ]
    }

    fn generate_nextjs(spec: &ProjectSpec) -> Vec<GeneratedFile> {
        let name = &spec.name;
        vec![
            GeneratedFile {
                path: "package.json".into(),
                content: format!(
                    "{{\n  \"name\": \"{}\",\n  \"version\": \"0.1.0\",\n  \"private\": true,\n  \"scripts\": {{\n    \"dev\": \"next dev\",\n    \"build\": \"next build\"\n  }}\n}}\n",
                    name
                ),
            },
            GeneratedFile {
                path: "src/app/page.tsx".into(),
                content: "export default function Home() {\n  return <main>Hello from SPS!</main>;\n}\n".into(),
            },
        ]
    }

    fn generate_tauri(spec: &ProjectSpec) -> Vec<GeneratedFile> {
        let mut files = Self::generate_nextjs(spec);
        files.push(GeneratedFile {
            path: "src-tauri/Cargo.toml".into(),
            content: format!(
                "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\ntauri = {{ version = \"2\", features = [] }}\n",
                spec.name
            ),
        });
        files.push(GeneratedFile {
            path: "src-tauri/src/main.rs".into(),
            content: "#![cfg_attr(not(debug_assertions), windows_subsystem = \"windows\")]\nfn main() {\n    tauri::Builder::default().run(tauri::generate_context!()).expect(\"error\");\n}\n".into(),
        });
        files
    }

    fn generate_generic(spec: &ProjectSpec) -> Vec<GeneratedFile> {
        vec![GeneratedFile {
            path: "README.md".into(),
            content: format!(
                "# {}\n\nGenerated by SPS Software Factory.\nKind: {}\n",
                spec.name, spec.kind
            ),
        }]
    }
}
